// Dados de exemplo usados só no MODO DEMONSTRAÇÃO (quando
// NEXT_PUBLIC_SHEETS_API_URL não está configurada). Contam uma história
// coerente de setembro/2026 pra todo o dashboard fazer sentido junto:
// salário caiu, aluguel foi pago, tem fatura de cartão em aberto, um
// parcelamento de notebook rolando e um orçamento estourado (Compras),
// pra mostrar o alerta funcionando de cara.

import type {
  Cartao,
  Categoria,
  Conta,
  FinanceState,
  Meta,
  Movimentacao,
  Orcamento,
  Recorrencia,
  Usuario,
} from "./types";

export const usuario: Usuario = { id: "user-tita", nome: "Tita" };

export const contas: Conta[] = [
  { id: "conta-nubank", nome: "Nubank", tipo: "corrente", saldoInicial: 1800 },
  { id: "conta-carteira", nome: "Carteira", tipo: "carteira", saldoInicial: 120 },
];

export const cartoes: Cartao[] = [
  {
    id: "cartao-nubank",
    nome: "Nubank Roxinho",
    limite: 4000,
    diaFechamento: 25,
    diaVencimento: 5,
    cor: "#8A05BE",
  },
  {
    id: "cartao-inter",
    nome: "Inter Gold",
    limite: 1500,
    diaFechamento: 10,
    diaVencimento: 17,
    cor: "#FF7A00",
  },
];

export const categorias: Categoria[] = [
  { id: "cat-salario", nome: "Salário", tipo: "receita" },
  { id: "cat-freela", nome: "Freelance", tipo: "receita" },
  { id: "cat-alimentacao", nome: "Alimentação", tipo: "despesa", cor: "#8FE0B0" },
  { id: "cat-delivery", nome: "Delivery", tipo: "despesa", cor: "#FFC98B" },
  { id: "cat-transporte", nome: "Transporte", tipo: "despesa", cor: "#8FCDF2" },
  { id: "cat-moradia", nome: "Moradia", tipo: "despesa", cor: "#C6A8F0" },
  { id: "cat-assinaturas", nome: "Assinaturas", tipo: "despesa", cor: "#D9A8ED" },
  { id: "cat-saude", nome: "Saúde", tipo: "despesa", cor: "#F4A0C0" },
  { id: "cat-lazer", nome: "Lazer", tipo: "despesa", cor: "#FCE28C" },
  { id: "cat-faculdade", nome: "Faculdade", tipo: "despesa", cor: "#8DE0C9" },
  { id: "cat-compras", nome: "Compras", tipo: "despesa", cor: "#F49AC2" },
];

export const movimentacoes: Movimentacao[] = [
  // ── Receitas ──
  {
    id: "mov-salario-set",
    contaId: "conta-nubank",
    categoriaId: "cat-salario",
    descricao: "Salário",
    tipo: "receita",
    valor: 4200,
    formaPagamento: "transferencia",
    dataCompra: "2026-09-05",
    dataVencimento: "2026-09-05",
    dataPagamento: "2026-09-05",
    status: "pago",
  },
  {
    id: "mov-freela-set",
    contaId: "conta-nubank",
    categoriaId: "cat-freela",
    descricao: "Projeto freelance",
    tipo: "receita",
    valor: 650,
    formaPagamento: "pix",
    dataCompra: "2026-09-08",
    dataVencimento: "2026-09-08",
    dataPagamento: "2026-09-08",
    status: "pago",
  },

  // ── Contas fixas do mês (via conta, não cartão) ──
  {
    id: "mov-aluguel-set",
    contaId: "conta-nubank",
    categoriaId: "cat-moradia",
    descricao: "Aluguel",
    tipo: "despesa",
    valor: 1400,
    formaPagamento: "pix",
    dataCompra: "2026-09-10",
    dataVencimento: "2026-09-10",
    dataPagamento: "2026-09-10",
    status: "pago",
  },
  {
    id: "mov-condominio-set",
    contaId: "conta-nubank",
    categoriaId: "cat-moradia",
    descricao: "Condomínio",
    tipo: "despesa",
    valor: 350,
    formaPagamento: "pix",
    dataCompra: "2026-09-10",
    dataVencimento: "2026-09-10",
    dataPagamento: "2026-09-10",
    status: "pago",
  },
  {
    id: "mov-internet-set",
    contaId: "conta-nubank",
    categoriaId: "cat-moradia",
    descricao: "Internet",
    tipo: "despesa",
    valor: 120,
    formaPagamento: "debito",
    dataCompra: "2026-09-12",
    dataVencimento: "2026-09-12",
    status: "pendente",
  },
  {
    id: "mov-academia-set",
    contaId: "conta-nubank",
    categoriaId: "cat-saude",
    descricao: "Academia",
    tipo: "despesa",
    valor: 99,
    formaPagamento: "debito",
    dataCompra: "2026-09-15",
    dataVencimento: "2026-09-15",
    status: "pendente",
  },

  // ── Supermercado (débito/pix, direto da conta) ──
  {
    id: "mov-mercado-1",
    contaId: "conta-nubank",
    categoriaId: "cat-alimentacao",
    descricao: "Supermercado",
    tipo: "despesa",
    valor: 220,
    formaPagamento: "debito",
    dataCompra: "2026-09-04",
    dataVencimento: "2026-09-04",
    dataPagamento: "2026-09-04",
    status: "pago",
  },
  {
    id: "mov-mercado-2",
    contaId: "conta-nubank",
    categoriaId: "cat-alimentacao",
    descricao: "Supermercado",
    tipo: "despesa",
    valor: 95,
    formaPagamento: "pix",
    dataCompra: "2026-09-09",
    dataVencimento: "2026-09-09",
    dataPagamento: "2026-09-09",
    status: "pago",
  },

  // ── Cartão Nubank: consumo do dia a dia (cai na fatura de 05/10) ──
  {
    id: "mov-ifood-1",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-delivery",
    descricao: "iFood",
    tipo: "despesa",
    valor: 45,
    formaPagamento: "credito",
    dataCompra: "2026-09-02",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-ifood-2",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-delivery",
    descricao: "iFood",
    tipo: "despesa",
    valor: 38,
    formaPagamento: "credito",
    dataCompra: "2026-09-05",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-ifood-3",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-delivery",
    descricao: "iFood",
    tipo: "despesa",
    valor: 52,
    formaPagamento: "credito",
    dataCompra: "2026-09-09",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-uber-1",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-transporte",
    descricao: "Uber",
    tipo: "despesa",
    valor: 28,
    formaPagamento: "credito",
    dataCompra: "2026-09-03",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-uber-2",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-transporte",
    descricao: "Uber",
    tipo: "despesa",
    valor: 28,
    formaPagamento: "credito",
    dataCompra: "2026-09-06",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-uber-3",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-transporte",
    descricao: "Uber",
    tipo: "despesa",
    valor: 28,
    formaPagamento: "credito",
    dataCompra: "2026-09-09",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-uber-4",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-transporte",
    descricao: "Uber",
    tipo: "despesa",
    valor: 28,
    formaPagamento: "credito",
    dataCompra: "2026-09-10",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-netflix",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-assinaturas",
    descricao: "Netflix",
    tipo: "despesa",
    valor: 44.9,
    formaPagamento: "credito",
    dataCompra: "2026-09-01",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },
  {
    id: "mov-spotify",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-assinaturas",
    descricao: "Spotify",
    tipo: "despesa",
    valor: 21.9,
    formaPagamento: "credito",
    dataCompra: "2026-09-01",
    dataVencimento: "2026-10-05",
    status: "pendente",
  },

  // ── Parcelamento: Notebook 10x no Nubank, comprado em julho ──
  {
    id: "mov-notebook-1",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-compras",
    descricao: "Notebook (1/10)",
    tipo: "despesa",
    valor: 350,
    formaPagamento: "credito",
    dataCompra: "2026-07-15",
    dataVencimento: "2026-08-05",
    dataPagamento: "2026-08-05",
    status: "pago",
    parcelaGrupoId: "parc-notebook",
    numeroParcela: 1,
    totalParcelas: 10,
  },
  {
    id: "mov-notebook-2",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-compras",
    descricao: "Notebook (2/10)",
    tipo: "despesa",
    valor: 350,
    formaPagamento: "credito",
    dataCompra: "2026-07-15",
    dataVencimento: "2026-09-05",
    dataPagamento: "2026-09-05",
    status: "pago",
    parcelaGrupoId: "parc-notebook",
    numeroParcela: 2,
    totalParcelas: 10,
  },
  {
    id: "mov-notebook-3",
    cartaoId: "cartao-nubank",
    categoriaId: "cat-compras",
    descricao: "Notebook (3/10)",
    tipo: "despesa",
    valor: 350,
    formaPagamento: "credito",
    dataCompra: "2026-07-15",
    dataVencimento: "2026-10-05",
    status: "pendente",
    parcelaGrupoId: "parc-notebook",
    numeroParcela: 3,
    totalParcelas: 10,
  },
  ...Array.from({ length: 7 }, (_, i) => {
    const numero = i + 4;
    const mes = 11 + i; // 11..17 -> vira novembro/2026 até maio/2027
    const ano = 2026 + Math.floor((mes - 1) / 12);
    const mesReal = ((mes - 1) % 12) + 1;
    const mm = String(mesReal).padStart(2, "0");
    return {
      id: `mov-notebook-${numero}`,
      cartaoId: "cartao-nubank",
      categoriaId: "cat-compras",
      descricao: `Notebook (${numero}/10)`,
      tipo: "despesa" as const,
      valor: 350,
      formaPagamento: "credito" as const,
      dataCompra: "2026-07-15",
      dataVencimento: `${ano}-${mm}-05`,
      status: "agendado" as const,
      parcelaGrupoId: "parc-notebook",
      numeroParcela: numero,
      totalParcelas: 10,
    };
  }),

  // ── Cartão Inter ──
  {
    id: "mov-roupas",
    cartaoId: "cartao-inter",
    categoriaId: "cat-compras",
    descricao: "Roupas",
    tipo: "despesa",
    valor: 180,
    formaPagamento: "credito",
    dataCompra: "2026-09-03",
    dataVencimento: "2026-09-17",
    status: "pendente",
  },
  {
    id: "mov-inter-fatura-anterior",
    cartaoId: "cartao-inter",
    categoriaId: "cat-lazer",
    descricao: "Fatura de agosto",
    tipo: "despesa",
    valor: 210,
    formaPagamento: "credito",
    dataCompra: "2026-08-06",
    dataVencimento: "2026-08-17",
    dataPagamento: "2026-08-17",
    status: "pago",
  },
];

export const recorrencias: Recorrencia[] = [
  { id: "rec-aluguel", descricao: "Aluguel", valor: 1400, categoriaId: "cat-moradia", diaVencimento: 10, frequencia: "mensal", ativo: true },
  { id: "rec-condominio", descricao: "Condomínio", valor: 350, categoriaId: "cat-moradia", diaVencimento: 10, frequencia: "mensal", ativo: true },
  { id: "rec-internet", descricao: "Internet", valor: 120, categoriaId: "cat-moradia", diaVencimento: 12, frequencia: "mensal", ativo: true },
  { id: "rec-academia", descricao: "Academia", valor: 99, categoriaId: "cat-saude", diaVencimento: 15, frequencia: "mensal", ativo: true },
  { id: "rec-netflix", descricao: "Netflix", valor: 44.9, categoriaId: "cat-assinaturas", diaVencimento: 1, frequencia: "mensal", ativo: true },
  { id: "rec-spotify", descricao: "Spotify", valor: 21.9, categoriaId: "cat-assinaturas", diaVencimento: 1, frequencia: "mensal", ativo: true },
];

export const orcamentos: Orcamento[] = [
  { id: "orc-alimentacao", categoriaId: "cat-alimentacao", mes: 9, ano: 2026, limite: 600 },
  { id: "orc-delivery", categoriaId: "cat-delivery", mes: 9, ano: 2026, limite: 300 },
  { id: "orc-transporte", categoriaId: "cat-transporte", mes: 9, ano: 2026, limite: 250 },
  { id: "orc-lazer", categoriaId: "cat-lazer", mes: 9, ano: 2026, limite: 200 },
  { id: "orc-compras", categoriaId: "cat-compras", mes: 9, ano: 2026, limite: 300 },
];

export const metas: Meta[] = [
  { id: "meta-reserva", nome: "Reserva de emergência", valorMeta: 10000, valorAtual: 2500 },
  { id: "meta-viagem", nome: "Viagem de fim de ano", valorMeta: 3000, valorAtual: 800, dataLimite: "2026-12-01" },
];

export const demoState: FinanceState = {
  usuario,
  contas,
  cartoes,
  categorias,
  movimentacoes,
  recorrencias,
  orcamentos,
  metas,
};
